# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.cache/wt [current_project]
set_property parent.project_path C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/imports/RAT_SOURCES/ALU.vhd
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/imports/RAT_SOURCES/CONTROL_UNIT.vhd
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/imports/RAT_SOURCES/FlagReg.vhd
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/imports/RAT_SOURCES/Flags.vhd
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/imports/RAT_SOURCES/PC.vhd
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/imports/RAT_SOURCES/PC_MUX.vhd
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/imports/RAT_SOURCES/ProgramCounter.vhd
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/imports/RAT_SOURCES/RAT_CPU.vhd
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/new/RandGen.vhd
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/imports/RAT_SOURCES/SCRATCH_RAM.vhd
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/imports/RAT_SOURCES/SP.vhd
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/imports/RAT_SOURCES/VGAdrive.vhd
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/imports/RatSimulator/prog_rom.vhd
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/imports/RAT_SOURCES/ram2k_8.vhd
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/imports/RAT_SOURCES/reg_file.vhd
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/imports/RAT_SOURCES/sseg_dec.vhd
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/imports/RAT_SOURCES/vgaDriverBuffer.vhd
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/imports/RAT_SOURCES/vga_clk_div.vhd
  C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/sources_1/imports/RAT_SOURCES/RAT_Wrapper.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/constrs_1/imports/CPE 233/Constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/evangeline/Desktop/FinalRATmu/FinalRAT.srcs/constrs_1/imports/CPE 233/Constraints.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top RAT_wrapper -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RAT_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RAT_wrapper_utilization_synth.rpt -pb RAT_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
